# Generated by Django 4.2.1 on 2023-06-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_system_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_short_id', models.CharField(max_length=200)),
                ('corp_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True)),
                ('cg_email', models.EmailField(max_length=254)),
                ('supervisor_name', models.CharField(default='', max_length=200)),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('n_1_name', models.CharField(default='', max_length=200)),
                ('n_1_email', models.EmailField(max_length=254)),
                ('asset_type', models.CharField(default='', max_length=200)),
                ('profile_picture', models.ImageField(upload_to='profile-picture/')),
                ('fte', models.CharField(default='', max_length=200)),
                ('cost_rate', models.CharField(default='', max_length=200)),
                ('onboard_type', models.CharField(max_length=200)),
                ('so_smart', models.CharField(default='', max_length=200)),
                ('pool_of_req', models.CharField(max_length=300)),
                ('so_r2d2', models.CharField(max_length=200)),
                ('onboard_date', models.DateTimeField(auto_now=True)),
                ('offboard_date', models.DateTimeField(blank=True)),
                ('backfill_person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Onboard_process_timeline',
            fields=[
                ('onboard_process_timeline_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('process_name', models.CharField(default='Process', max_length=200)),
                ('process_status', models.CharField(default='Not Started', max_length=200)),
                ('process_description', models.CharField(default='New Process', max_length=200)),
                ('process_start_date', models.DateTimeField(auto_now=True)),
                ('process_end_date', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboard_timeline_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('team_leader_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tl_created_by', to=settings.AUTH_USER_MODEL)),
                ('team_leader_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDA',
            fields=[
                ('team_da_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='da_created_by', to=settings.AUTH_USER_MODEL)),
                ('team_da_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='Team', max_length=200)),
                ('team_description', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_created_by', to=settings.AUTH_USER_MODEL)),
                ('team_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.teamda')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.teamleader')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('project_role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_role_name', models.CharField(default='Default Name', max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_role_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('project_code_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_code', models.CharField(default='', max_length=200)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectcode_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Onboarding_ticket_relation',
            fields=[
                ('onboard_ticket_relation', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(default='TICKET', max_length=200)),
                ('ticket_short_desc', models.CharField(default='', max_length=200)),
                ('ticket_long_desc', models.CharField(default='', max_length=500)),
                ('raised_on', models.DateTimeField(auto_now=True)),
                ('ticket_link', models.URLField(default='#')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('timeline_relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.onboard_process_timeline')),
            ],
        ),
        migrations.CreateModel(
            name='Onboard_registration',
            fields=[
                ('onboard_reg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboard_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee_onboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.employee')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboard_raised_by', to='DatabaseEngine.employee')),
            ],
        ),
        migrations.AddField(
            model_name='onboard_process_timeline',
            name='onboard_reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.onboard_registration'),
        ),
        migrations.AddField(
            model_name='onboard_process_timeline',
            name='process_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_created_by', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.team')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(default='Default Location', max_length=200)),
                ('location_short_name', models.CharField(default='LOC', max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('grade_name', models.CharField(default='Analyst', max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_To_Project_Mapping',
            fields=[
                ('e2p_map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_percent', models.CharField(max_length=200)),
                ('mapped_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.employee')),
                ('mapped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.projectcode')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.module'),
        ),
        migrations.AddField(
            model_name='employee',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='spoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spoc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.team'),
        ),
    ]
