# Generated by Django 4.2.1 on 2023-07-06 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DatabaseEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_obj',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='backfill_person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='backfill', to=settings.AUTH_USER_MODEL),
        ),
    ]
