# Generated by Django 4.2.1 on 2023-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0002_employee_emp_obj_alter_employee_backfill_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
