# Generated by Django 4.2.1 on 2023-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0004_employee_offboard_started_employee_onboard_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_registration',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboard_registration',
            name='closed_on',
            field=models.DateTimeField(),
        ),
    ]
