# Generated by Django 4.2.1 on 2023-07-06 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0005_onboard_registration_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_registration',
            name='closed_on',
            field=models.DateTimeField(default=datetime.date(9999, 12, 31)),
        ),
    ]
