# Generated by Django 4.2.1 on 2023-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0006_alter_onboard_registration_closed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard_registration',
            name='closed_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
