# Generated by Django 4.2.1 on 2023-07-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0007_alter_onboard_registration_closed_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboard_registration',
            name='closed_on',
        ),
    ]
