# Generated by Django 4.2.1 on 2023-07-06 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0008_remove_onboard_registration_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboard_registration',
            name='closed_on',
            field=models.DateTimeField(default=datetime.date(9999, 12, 31)),
        ),
    ]
