# Generated by Django 4.2.1 on 2023-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0009_onboard_registration_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_fancy',
            field=models.CharField(default='', max_length=500),
        ),
    ]
