# Generated by Django 4.2.1 on 2023-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0010_location_location_fancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='Team', max_length=4),
        ),
    ]
