# Generated by Django 4.2.1 on 2023-07-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0011_alter_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.grade'),
        ),
    ]
