# Generated by Django 4.2.1 on 2023-07-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0013_employee_verfied_background_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
