# Generated by Django 4.2.1 on 2023-07-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0014_projectrole_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
