# Generated by Django 4.2.1 on 2023-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseEngine', '0015_projectcode_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcode',
            name='project_description',
            field=models.CharField(default='Project Code', max_length=200),
        ),
    ]
