# Generated by Django 3.2.12 on 2023-07-12 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DatabaseEngine', '0016_projectcode_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Module_Registration',
            fields=[
                ('app_register_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=10)),
                ('app_short_name', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Access_To_App_Portal',
            fields=[
                ('access_registration_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_validity_end', models.DateTimeField(default=datetime.date(9999, 12, 31))),
                ('access_provided_on', models.DateTimeField(auto_now=True)),
                ('access_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DatabaseEngine.app_module_registration')),
                ('access_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_user', to=settings.AUTH_USER_MODEL)),
                ('provided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provided_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
